package com.farm_erp.trails.statics;

public enum _Section_Enums {

    ROLES, BUSINESS,

    GENERAL_BUSINESS_SETTINGS,
    DISTRICTS, DISTRICT_OFFICES, VILLAGE, FARMER_TYPE,

    FARMERS, AID, AID_BLOCK, BLOCK, BLOCK_CYCLE,CANE_VARIETY, CROP_TYPES,

    VEHICLES,TICKETS,TRANSPORTFARES, WEIGHBRIDGE, TRANSPORTERS, PERMIT,

    SESSION, TRANSACTIONS

}
